# Generated by Django 3.2.1 on 2021-06-14 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_preference'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='price',
            field=models.CharField(blank=True, default=None, max_length=20, null=True),
        ),
    ]
