# Generated by Django 3.2.1 on 2021-06-15 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_article_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='sentiment',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
    ]
